{% set name = "splinecalib" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b14e47388a4c012aa99c085fcad68404e01c09a09234c6e6a4aab0cb8fd406b2

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - wheel
    - cython >=3.0.0
    - numpy >=1.23.5
    - scipy >=1.6
    - pip
  run:
    - python
    - pandas >=1.3
    - scipy >=1.6
    - matplotlib-base >=1.0
    - joblib >=0.14.1

test:
  imports:
    - loss_fun_c
    - splinecalib
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/numeristical/splinecalib
  summary: Simple, fast, extensible JSON encoder/decoder for Python
  description: |
    SplineCalib is a Python package for calibrating
    ML models using smoothing splines. 
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/numeristical/splinecalib

extra:
  recipe-maintainers:
    - philip-khor
