{% set name = "splinecalib" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05453db0c419e42a7e939b64936af7232cb10b0a594cedbe2a972c9d392c80ac

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.3
    - matplotlib-base

test:
  imports:
    - splinecalib
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/numeristical/splinecalib
  summary: Simple, fast, extensible JSON encoder/decoder for Python
  description: |
    SplineCalib is a Python package for calibrating
    ML models using smoothing splines. 
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/numeristical/splinecalib

extra:
  recipe-maintainers:
    - philip-khor
